### ISSUE TITLE
Save issues

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#209] opened 2018-05-23 03:20 UTC
Same issue from #193 is still happening, some elements are unlinking and moving back to their last position.

Few things I often do.
-Click save during save process,
-Save right after a save without doing anything else
-Save but during the save process move around and edit something else and then save again

So far still not good repro steps.

**Comment by Luffyyy** [comment] 2018-05-23 17:11
clicking save while saving does nothing(there's literally a check to make sure you don't save twice)

I think it's a rare issue.

**Comment by RexTheWho** [comment] 2018-05-24 02:16
Its common enough that Ive stopped working on proper linking in my projects.
If Ive placed and set up 50 elements and then for whatever reason it doesnt save right I have to relink and check those 50 elements.

**Comment by RexTheWho** [comment] 2018-05-24 06:08
Noticed something, I linked a keycard to an ElementUnitSequence that gets triggered on startup and when I select the keycard it doesnt show the Startup ElementUnitSequence.

It does still show a different ElementUnitSequence that is in charge of making it visible later on.

**Comment by RexTheWho** [comment] 2018-05-24 10:10
Few attempts to get a reproduce step, no steps yet but seems that sometimes changes made to an element arent being applied, meaning on save/restart they revert.

Easiest to spot on UnitSequences since you can check if its been linked or not properly.

**Comment by Nepgearsy** [comment] 2018-05-25 06:05
had the exact same problem a 2 days ago, but never could get it back

**Comment by NoName0D** [comment] 2018-05-26 11:13
I have this issue too, i opened an issue few days ago with enable elements and disable elements. But the problem is links in general. They sometimes just don't save.

**Comment by Dilbert-JonhonsonThe999th** [comment] 2018-05-26 21:00
Exact same issue, and it happens constantly. It's unbelievably annoying to have to reload your heist in editor up to 3 (!) times and redo EVERY previous link because the editor decided not save them.

**Comment by Luffyyy** [comment] 2018-05-27 01:16
Sadly it will take me time to fix as it's not happening all the time / no way to reproduce.
I am also gonna be busy this week sadly so I don't know if I'll have time.

**Comment by Nepgearsy** [comment] 2018-05-30 13:03
seems to only happening on old maps, and god this is frustrating.

**Comment by NoName0D** [comment] 2018-06-01 12:14
I think, i figure it out and i can replicate the bug. So when you link Elements or units, then save the first time everything gets saved, but if you then continue to link stuff and save after the first save, then nothing gets saved.

**Comment by Luffyyy** [comment] 2018-06-06 10:13
Sorry for the trouble this issue has caused, it should be fixed now.

**Closed** 2018-06-06 10:13 UTC
