### ISSUE TITLE
VO materials not porting in base game heist clones

### ISSUE THREAD

**Issue by DiscendoVox** [simon-wh/PAYDAY-2-BeardLib-Editor#73] opened 2018-03-14 22:48 UTC
Basically what it says in the title.  It appears that VO stream material consistently fails to port over when a vanilla heist is cloned into the editor. I've had a couple folks check across a handful of heists. The heist won't crash, but briefing and debriefing lines, as well as all VO lines called by the heist objectives and other elements will be silent.

**Comment by Luffyyy** [comment] 2018-03-15 15:32
Caused by absence of world sounds package, will be fixed next update.

**Closed** 2018-03-15 17:43 UTC
